<a href="https://colab.research.google.com/github/srj7/DSCourse/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [5]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


**Question 2**

In [14]:
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

5
9
7
8
6
3
4
1
2
0
[5 9 7 8 6 3 4 1 2 0]
[0 1 2 3 4 5 6 7 8 9]


**Question 3**

In [22]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


**Question 4**

In [49]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


**Question 5**

In [56]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.8418624  0.11132147 0.71759827]
 [0.72996371 0.89752563 0.12768244]
 [0.80129902 0.36961897 0.6120731 ]
 [0.29055544 0.61678773 0.80531161]
 [0.31991061 0.26879361 0.88770152]
 [0.59006031 0.28584399 0.16354731]]

[[0.8418624  0.11132147 0.71759827 0.29055544 0.61678773 0.80531161]
 [0.72996371 0.89752563 0.12768244 0.31991061 0.26879361 0.88770152]
 [0.80129902 0.36961897 0.6120731  0.59006031 0.28584399 0.16354731]]


**Question 6**

In [82]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3]))
